function Hysplit_notes = mar_Hysplit_text_input_1801


Hysplit_notes = strvcat('-72',...    % length of trajectories - here 5 days backward
'0',...                               % type of vertical motion - here "data" or 3D wind field
'1000.0',...                         % top of the model domain in meters (trajectories terminate if height is reached)
'6',...                               % number of meteorological files to be loaded - here 2 files... 
'/Users/qingn/Hysplit4/working/PASE/',...       % ...for 5d trajectories
'gdas1.dec17.w5',...
'/Users/qingn/Hysplit4/working/PASE/',...       % GDAS meteorological files - append files as needed to provide data for... 
'gdas1.dec17.w3',...                  % ...longer trajectories or more research flights 
'/Users/qingn/Hysplit4/working/PASE/',...       % GDAS meteorological files - append files as needed to provide data for... 
'gdas1.dec17.w4',...                  % ...longer trajectories or more research flights 
'/Users/qingn/Hysplit4/working/PASE/',...       % GDAS meteorological files - append files as needed to provide data for... 
'gdas1.jan18.w1',...                  % ...longer trajectories or more research flights 
'/Users/qingn/Hysplit4/working/PASE/',...       % GDAS meteorological files - append files as needed to provide data for... 
'gdas1.jan18.w2',...                  % ...longer trajectories or more research flights 
'/Users/qingn/Hysplit4/working/PASE/',...       % GDAS meteorological files - append files as needed to provide data for... 
'gdas1.dec17.w2',...                  % ...longer trajectories or more research flights 
'/Users/qingn/Hysplit4/working/Conversionfiles_1801/'...
); % output folder of HYSPLIT computations in text format


end